### ISSUE TITLE
Breaking change by using ! is not working

### ISSUE THREAD

**Issue by rodrigomata** [jscutlery/semver#454]
If I try to indicate a breaking change as it [can be done with Conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-scope-and--to-draw-attention-to-breaking-change), this plugin won't recognize it as such and will apply only the type.

For example `feat(scope)!: not backwards compatible` will only update `0.0.1` to `0.1.0` instead of the desired `1.0.0`.

**Comment by rodrigomata** [comment]
[This](https://github.com/jscutlery/semver/issues/412#issuecomment-1046040237) is the workaround

**Comment by edbzn** [comment]
Hi @rodrigomata, this is because semver uses the [Angular convention](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit-message-footer) by default, which does not include the `feat(scope)!:` breaking change rule. Hopefully we just released a new option `--preset conventional` to support the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-scope-and--to-draw-attention-to-breaking-change) specification.
