### ISSUE TITLE
Option to only generate changelog

### ISSUE THREAD

**Issue by cakeinpanic** [jscutlery/semver#455]
Hi!
I made few releases manually and now I want to generate proper changelog for each version which were already published.

I put correct tags on corresponding commits, Is there a way to run this task to only parse git log and generate proper changelog?

**Comment by edbzn** [comment]
Hi, I never had this scenario so I'm not entirely sure but I think it will parse commits since the last version and generate the changelog, it will skip the logs before the last version, the one you created manually, and therefore not insert them into the changelog file. At the moment there's no way to override the git reference from where it calculates the changes. A hack would be to temporarily remove your tags locally so it will compute the logs since the first commit, but that's very not ideal.

**Comment by cakeinpanic** [comment]
@edbzn I found a way to do it – remove all local tags, then checkout each version commit from first to last, run `version`, stash, go to other commit, unstash, run `version`, repeat until success

It worked, thank you
