### ISSUE TITLE
Any plan on supporting 'semantic-release'  ?

### ISSUE THREAD

**Issue by tinesoft** [jscutlery/semver#71]
Hi semver Team,

Thanks for the plugin.

Any chance on supporting https://github.com/semantic-release/semantic-release in addition to standard-version (users could decide through a new option on the schematics for e.g)?

It has the advantage of fully automating the release (no manually operation at all),
integrates with NPM, Github Releases out-of-the-box (closing #70), etc.

**Comment by edbzn** [comment]
Hi, thanks for your feedback.

> It has the advantage of fully automating the release (no manually operation at all)

That's what we have in mind, our next goal is to provide package publish to allow fully automate release cycle (#32) . To achieve this we started working a dedicated deploy builder. We choose to improve this one [ngx-deploy-npm](https://github.com/bikecoders/ngx-deploy-npm/pull/40) to make it compatible with Nx workspace, then we want to integrate this builder directly in this semver plugin.

> Any chance on supporting https://github.com/semantic-release/semantic-release in addition to standard-version (users could decide through a new option on the schematics for e.g)?

The problem with semantic-release is the same that we're facing with [standard-version](https://github.com/conventional-changelog/standard-version), it does not suit well for monorepos, especially with the synced mode. The very interesting thing with this package is the plugin collection, I will investigate more on how we could provide this. 

What do you think @yjaaidi ?

**Comment by yjaaidi** [comment]
Thank you @tinesoft for the feedback.
+1 @edbzn. We need plugins! 

I can see 3 different approaches:
1. handling publishing & deployment using plugins.
2. handling `npm publish` in `@jscutlery/semver` but what about github release, or even python's pip or deploying apps to firebase or vercel etc... too much surface for the lib. 
3. not handling publish & deploy. This is the current state of `@jscutlery/semver` and it means extra setup for everyone.

So plugins are clearly the way to go.

Instead of the `ngx-deploy-npm` approach, we could implement an adapter that makes `semantic-release` plugins compatible with `@jscutlery/semver` and we would then use `@semantic-release/npm`. The main challenge is reverse-engineering the type of the `context` object which is used everywhere 😅

The configuration would look something like this:

```json
"targets": {
  "version": {
    "executor": "@jscutlery/semver:version",
    "options": {
      "plugins": [
        "@semantic-release/npm"
      ]
    }
  }
},
```
We would have to detect that `@semantic-release/npm` is a `semantic-release` plugin and we would wrap it with our adapter (e.g. `SemanticReleaseAdapter implements SemverPlugin`).

**Comment by edbzn** [comment]
I'm agree, the first approach looks the way to go but it raises some questions :
- do we drop `standard-version` as it does not support hooking into release steps programmatically?
- do we keep `standard-version` and we make the plugin system `semantic-release` compatible only?
- what about the synced mode in addition with `semantic-release`, how we deploy multiple packages at once?

**Comment by tinesoft** [comment]
Hello guys,


Thanks for considering `semantic-release`! I do think it would be a great addition to the plugin💡 

Maybe this project might help for the implementation? https://github.com/twittwer/nx-tools. 
It's another collection of nx plugins that uses `semantic-release`'s API and a custom `release` target.
I shamelessly reuse the same for my own collection of nx plugins (https://github.com/tinesoft/nxrocks) 😇 .
It is not perfect (to much manual overrides), but it can be a good starting point.

**Comment by yjaaidi** [comment]
> * do we drop `standard-version` as it does not support hooking into release steps programmatically?
> * do we keep `standard-version` and we make the plugin system `semantic-release` compatible only?

It is not necessary yet as we don't have to support all hooks. For now, we just need a `publish` hook.
We can add others later. Most of them like `prepare` can be called before calling `standard-version` so we don't have to get rid of it yet.

> * what about the synced mode in addition with `semantic-release`, how we deploy multiple packages at once?

Based on the workspace definition, we know which builder is used and we have the output path in the configuration.
This way we can `build` every package and `publish` it using the given plugin.

What do you think?

**Comment by edbzn** [comment]
I think we need more than the `publish` hook, the `semantic-release/npm` plugin uses :

- verifyConditions 
- prepare 
- addChannel
- publish

Users would expect that the plugin work the same way as with semantic-release, so we need to implement these hooks.

**Comment by yjaaidi** [comment]
Actually, it all depends on our goals.
Should we just try to reuse plugins like `@semantic-release/npm` & others to deploy apps / publish libs? 
Or do we want to support all `@semantic-release` plugins?

It's probably the same effort for both but the second provides more value 😊

Instead of just supporting `@semantic-release` plugins, I think we can split this into two features:
- Defining a plugin system for `semver`
- Creating a `@jscutlery/semantic-release-plugin-adapter` that wraps `@semantic-release` plugins

I am thinking about something like this:
```ts
interface Plugin {
  prepare?(???): unknown | Promise<unknown> | Observable<unknown>
  publish?(???)
  success?(???) // do we need this? there is a slack plugin for example but I don't think that it's up to semver tools to handle this.
  fail?(???) // same here
}
```

We would call `prepare` before `standard-version` and then `publish` afterward.

Then we would have the semantic-release adapter:

```ts
class SemanticReleasePluginAdapter {
  prepare() {
    plugin.prepare()
  }
  publish() {
    plugin.addChannel()
    plugin.publish()
  }
}
```

In terms of configuration, it would be the same:
```json
{
  "plugins": [
    "@semantic-release/npm",
    "@jscutlery/semver-github-release"
  ]
}
```

and the plugin loader's heuristics should detect if it's a semver plugin or a semantic release one.

The main challenge for `SemanticReleasePluginAdapter` is to re-construct a `semantic-release` context.
The second challenge is to check how plugin behaviors overlap with `semver`. For example, `@semantic-release/npm` updates the `package.json` version.

What do you think @edbzn?

**Comment by petergrau** [comment]
Maybe https://github.com/pmowrer/semantic-release-monorepo is also worth a look and how they do it?

**Comment by guiseek** [comment]
thanks for the contribution with the community, i'm looking forward to this plugin. if I can be useful for use case testing, it will be my pleasure

**Comment by guiseek** [comment]
thanks for the contribution with the community, i'm looking forward to this plugin. if i can be useful for use case testing, it will be my pleasure

**Comment by edbzn** [comment]
We're close to the end with semantic-release plugin support, we're facing the last tricky issue which is forwarding the right context object to the plugins.

**Comment by Charlinho** [comment]
@edbzn, Great! if you any help, I can contribute with your work.
thanks!

**Comment by LayZeeDK** [comment]
ngworkers are interested in using these plugins:
- `@semantic-release/github`
- `@semantic-release/npm`

**Comment by yjaaidi** [comment]
Closing this issue to regroup the discussions here #167.
