### ISSUE TITLE
Add support for @nx/devkit v19.0.0

### ISSUE THREAD

**Issue by bjornharvold** [jscutlery/semver#814]
Came with the last major release of Nx today

**Comment by ak274** [comment]
v5 already works with nx v18.. 
It should be support for v19?

**Comment by edbzn** [comment]
Hey, will work on it soonish, I think there's no major breaking change.

**Comment by bjornharvold** [comment]
👋🏻 @edbzn have an ETA for us? 🫶🏼

**Comment by smitev** [comment]
what is the status of the work for upgrading to @nx v19?

**Comment by dianjuar** [comment]
A workaround for this problem is forcing `@jscutlery/semver` to use Nx V19. This is not ideal; it could lead to unpredictable results if Nx19 contains a breaking change.

For `npm`
```json
"overrides": {
    "@jscutlery/semver": {
      "@nx/devkit": "YOUR.CURRENT.VERSION"
    }
  }
```

> If you are not using `npm` as a package manager, you would need to search, which is the equivalent of `overrides`

---

This seems safe to use, I did it on `ngx-deploy-npm` and everything seems to be [working as expected](https://github.com/bikecoders/ngx-deploy-npm/pull/606).

**Comment by edbzn** [comment]
Guys I'm on vacation without my pc, you can force semver to use nx v19 there's no breaking change.

**Comment by dianjuar** [comment]
Should this issue be closed?

Semver supports Nx19 since august on [V5.3.0](https://github.com/jscutlery/semver/blob/main/packages/semver/CHANGELOG.md#530-2024-08-02)
